# typed: false
# frozen_string_literal: true

# Homebrew formula for netspd, installing prebuilt release binaries.
# Generated by netspd's release workflow — do not edit by hand.
class Netspd < Formula
  desc "Beautiful network speed test for the terminal, with a hypercar tachometer"
  homepage "https://github.com/TarunVishwakarma1/netspd"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.7/netspd-v0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "1b556b6fb034b70ff40e679418ba69fbf88444b88460acc186aa326b9b135dc2"
    else
      url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.7/netspd-v0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "d63cdbd4330f9ea36be95c228d5b28d8a1ca2f882b5c879e7a174420c774791e"
    end
  end

  on_linux do
    url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.7/netspd-v0.1.7-x86_64-unknown-linux-musl.tar.gz"
    sha256 "7f042ae8ad800d8c97ffb3d469cfc847fe35cde27001f90dcb7aea819ff42677"
  end

  def install
    bin.install "netspd"
    if File.exist?("netspd.1")
      man1.install "netspd.1"
      bash_completion.install "completions/netspd.bash" => "netspd"
      zsh_completion.install "completions/netspd.zsh" => "_netspd"
      fish_completion.install "completions/netspd.fish"
    end
  end

  test do
    assert_match "netspd #{version}", shell_output("#{bin}/netspd --version")
  end
end
