# typed: false
# frozen_string_literal: true

# Homebrew formula for netspd, installing prebuilt release binaries.
# Generated by netspd's release workflow — do not edit by hand.
class Netspd < Formula
  desc "Beautiful network speed test for the terminal, with a hypercar tachometer"
  homepage "https://github.com/TarunVishwakarma1/netspd"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.2/netspd-v0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "4acbbd6db124aefd30584692292e683919dee41204b29da87f7ede6f45139c75"
    else
      url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.2/netspd-v0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "743725d612de67169d507294d22f8fd45f6db9ae92faaf1d0baf4a36900a05b0"
    end
  end

  on_linux do
    url "https://github.com/TarunVishwakarma1/netspd/releases/download/v0.1.2/netspd-v0.1.2-x86_64-unknown-linux-musl.tar.gz"
    sha256 "451e24bbaafcedc55c6657d94e7b77f08e26a66ed8c8998164c16fa2ac826963"
  end

  def install
    bin.install "netspd"
  end

  test do
    assert_match "netspd #{version}", shell_output("#{bin}/netspd --version")
  end
end
